name: PR assignment
on:
    pull_request_target:
        types: [opened, edited, synchronize, reopened, ready_for_review]
        
permissions:
  contents: read
  issues: write
  pull-requests: write
  
jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Request Reviewers
        uses: actions/github-script@v6
        with:
          script: |
            const reviewers = ['jinhwankim6557']; // reviewers

            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              reviewers: reviewers
            });
      - name: Assign PR author and reviewers
        uses: actions/github-script@v6
        with:
          script: |
            const assignees = ['jinhwankim6557']; // assignees
            
            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              assignees: assignees
            });
